classifier/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "classifier"

urlpatterns = [
    path('', views.index, name='index'),
    path('start_classification', views.start_classification, name='start_classification'),
    path('download', views.serve_downloadable, name='download'),
]

concreteClassifierApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('classifier.urls', namespace='classifier')),
]

urlpatterns += staticfiles_urlpatterns()

classifier/models.py
from django.db import models
import pathlib, uuid

# Create your models here.

classifier/forms.py
from django import forms

classifier/views.py
import shutil
from django.http import FileResponse
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from concreteClassifierApp.settings import BASE_DIR
import os
import io, zipfile, requests
import subprocess
from pandas import DataFrame as pd
from pandas import read_csv
from concrete.ml.deployment import FHEModelServer
import hashlib

def hash_file(filename):
   """"This function returns the SHA-1 hash
   of the file passed into it"""

   # make a hash object
   h = hashlib.sha1()

   # open file for reading in binary mode
   with open(filename,'rb') as file:

       # loop till the end of the file
       chunk = 0
       while chunk != b'':
           # read only 1024 bytes at a time
           chunk = file.read(1024)
           h.update(chunk)

   # return the hex representation of digest
   return h.hexdigest()

# Create your views here.
def index(request):
    
    return render(request, 'index.html', context={'classes_list':{0: 'B.1.1.529 (Omicron)', 1: 'B.1.617.2 (Delta)', 2: 'B.1.621 (Mu)', 3: 'C.37 (Lambda)'}})

def start_classification(request):

    clean_predictions_folder()

    count = 0
    model_path = os.path.join(BASE_DIR, "classifier/Compiled Model") 
    keys_path = os.path.join(BASE_DIR, "classifier/keys")
    keys_file = request.FILES['keys_file']
    pred_dir = os.path.join(BASE_DIR, "classifier/predictions")

    data = request.FILES['inputs'].read().strip()

    enc_file_list = []

    print(f"Data received from client is {data[:200]}")
    count += 1
    serialized_evaluation_keys = keys_file.read()
    encrypted_prediction = FHEModelServer(model_path).run(data, serialized_evaluation_keys)
    pred_file_name = f"encrypted_prediction_{count}.enc"
    pred_file_path = os.path.join(pred_dir, pred_file_name)
    with open(pred_file_path, "wb") as f:
        f.write(encrypted_prediction)

    #send all predictions as a zip file to client
    enc_file_list.append(pred_file_path)

    zipfile = create_zip(enc_file_list)

    return zipfile

def create_zip(file_list):
    count = 0
    zip_filename = os.path.join(BASE_DIR, "classifier/predictions/enc_predictions.zip")
    zip_download_name = "enc_predictions.zip"
    buffer = io.BytesIO()
    zip_file = zipfile.ZipFile(buffer, 'w')
    
    for filename in file_list:
        count += 1
        with open(filename, "rb") as file_read:
            zip_file.write(filename, f"encrypted_prediction_{count}.enc")
    zip_file.close()

    #craft download response    
    resp = HttpResponse(buffer.getvalue(), content_type = "application/force-download")
    resp['Content-Disposition'] = f'attachment; filename={zip_download_name}'

    return resp

def clean_predictions_folder():
    pred_dir = os.path.join(BASE_DIR, f"classifier/predictions")

    if(os.listdir(pred_dir)):
        for f in os.listdir(pred_dir):
            os.remove(os.path.join(pred_dir, f))

def serve_downloadable(request):
    filename = request.GET.get('filename')

    if request.method == "GET":
        response = download_file(filename=filename)
        return response
    elif request.method == "POST":
        return HttpResponse("Please use a GET request to access this endpoint.")

def download_file(filename):
    #assume server will always have latest version of software
    download_directories = [
        os.path.join(BASE_DIR, "classifier/ClientDownloads"),
        os.path.join(BASE_DIR, "classifier/AlternativeDashingDownloads"),
        os.path.join(BASE_DIR, "classifier/Compiled Model")
    ]

    for dir in download_directories:
        if filename in os.listdir(dir):
            download_fname = os.path.join(dir, filename)
            response = FileResponse(open(download_fname, 'rb'))
            response['Content-Disposition'] = f'attachment; filename={filename}'
            response['hash']=hash_file(download_fname)
            print(f"Serving {filename} to client...")
            return response

classifier/templates/index.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>FHE-enabled SARS-CoV-2 Sequence Classifier (Server-Side)</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
  </head>

  <body>

    <form action="{% url 'classifier:start_classification' %}" method="post">
      {% csrf_token %}
      <div class="form-group mt-3" hidden>
          <label class="mr-2">Upload your encrypted inputs:</label>
          <input type="file" name="file">
      </div>
      <div class="form-group mt-3" hidden>
          <label class="mr-2">Upload your evaluation keys (.ekl):</label>
          <input type="file" name="keys_file">
      </div>
    </form>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <h1 class="display-3">FHE-enabled SARS-CoV-2 Sequence Classifier</h1>
          <p>This is the homepage for the server-side application of an FHE-enabled SARS-CoV-2 classification system. This site hosts links to the Github repository of the application, and the download link for the client GUI app (requirements are listed in requirements.txt in the Github repository).</p>
          <p><a class="btn btn-primary btn-lg" href="https://github.com/bjorgkav/concreteml-covid-classifier" role="button" target="_blank">Access the Github repository &raquo;</a></p>
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <div class="col-md-4">
            <h2>Technologies Used</h2>
            <ul>
              <li><a href="https://github.com/zama-ai/concrete-ml" target="_blank" rel="noopener noreferrer">Concrete-ML v1.0.3</a></li>
              <li><a href="https://www.djangoproject.com/" target="_blank" rel="noopener noreferrer">Django Framework v4.2.1</a></li>
              <li><a href="https://github.com/dnbaker/dashing" target="_blank" rel="noopener noreferrer">Dashing by dnbaker</a></li>
              <li><a href="https://github.com/TomSchimansky/CustomTkinter" target="_blank" rel="noopener noreferrer">CustomTkinter v5.1.3</a></li>
              <li><a href="https://pandas.pydata.org/" target="_blank" rel="noopener noreferrer">Pandas v2.0.1</a></li>
            </ul>
            <p><a class="btn btn-secondary" href="https://github.com/bjorgkav/concreteml-covid-classifier/blob/main/requirements.txt" target="_blank" role="button">Show more &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>Client-side application</h2>
            <p>This classification system is intended to be used with the client-side GUI application, which can be accessed here (see requirements.txt for the required packages):</p>
            <p><a class="btn btn-secondary" href="https://github.com/bjorgkav/concreteml-covid-classifier/blob/main/client/GUI/Client_GUI_App.py" role="button">Download the Client-side GUI Application &raquo;</a></p>
          </div>
          <div class="col-md-4">
            <h2>SARS-CoV-2 Strains Currently Supported</h2>
            <ul>
              {% for value in classes_list.values %}
              <li>{{ value }}</li>
              {% endfor %}
            </ul>
          </div>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>

    <footer class="container">
      <p>Website developed by Johann Benjamin P. Vivas (last updated June 3, 2023)</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/vendor/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

classifier/templates/index2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FHE-enabled SARS-CoV-2 Sequence Classifier (Server-Side)</title>
    <link rel="stylesheet" href="{% static 'getform.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
    <div class="col-md-6 offset-md-3 mt-5">
        <h1>FHE-enabled SARS-CoV-2 Sequence Classifier (Server-Side)</h1>
        <p>Powered by Concrete-ML</p>
        <hr>

        <p>Submit your encrypted inputs and evaluation keys to the classifier to have your encrypted sequences classified between the following variants:</p>

        <ul>
            {% for key, value in classes_list.items %}
                <li> {{ value }} </li>
            {% endfor %}
        </ul>

        <p>Note that your prediction output will be a downloadable .ZIP file containing the .enc prediction files for each of your submitted strains.</p>

        <form accept-charset="UTF-8" action="{% url 'classifier:start_classification' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group mt-3">
                <label class="mr-2">Upload your encrypted inputs:</label>
                <input type="file" name="file">
            </div>
            <div class="form-group mt-3">
                <label class="mr-2">Upload your evaluation keys (.ekl):</label>
                <input type="file" name="keys_file">
            </div>
            <!-- {{ form.as_p }} -->
            <hr>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div> 
</body>
</html>

classifier/templates/orig_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'getform.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
    <div class="col-md-6 offset-md-3 mt-5">
        <h1>FHE-enabled SARS-CoV-2 Sequence Classifier</h1>
        <p>Powered by Concrete-ML</p>
        <form accept-charset="UTF-8" action="{% url 'classifier:process_submit' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group mt-3">
                <label class="mr-2">Upload your Sequence:</label>
                <input type="file" name="file">
            </div>
            <!-- {{ form.as_p }} -->
            <hr>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div> 
</body>
</html>

classifier/templates/upload_success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'getform.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
    <div class="col-md-6 offset-md-3 mt-5">
        <h1>FHE-enabled SARS-CoV-2 Sequence Classifier</h1>
        <p>Powered by Concrete-ML</p>

        <h3>Upload successful!</h3>

        <p>FASTA Accession ID (Assuming GISAID): {{ accession_id }}</p>

        <p>First Line: {{ metadata }}</p>

        <p>Truncated FASTA Sequence Size (Removed first 20,000 bases): {{ truncate_output_length }}</p>

        <p>Content: {{ truncate_output|slice:"0:10" }}...</p>
        </ul>
    </div> 
</body>
</html>